### PR TITLE
Restructuring code for internal quantum capacitance calculation

### PR DESCRIPTION
**Pull request by holdymoldy**
Overpotential is replaced by V_dl (double-layer voltage) and the relationship between applied voltage (V_app) and V_dl is calculated if the relevant flag is set in `compute_k_MHC_DOS`. This is inefficient because the calculation is repeated for every call to `compute_k_MHC_DOS`. In the future this step can potentially be performed by the user and the output written to file.

### CODE REVIEW

**Comment by rkurchin** [comment]
I'm happy to merge this if you're done with it...I see there's a `#TODO` there, is that for sometime down the line?

Also, I assume this is all the changes you plan to make for now? If so, I can hopefully start putting the rest of the stuff in later this week.

**Comment by holdymoldy** [comment]
Sorry I forgot to remove that `TODO`. I will also change the notation on the `redox` functions that I added. Just wanted to be sure you were okay with how the changes looked on the main function.

**Comment by rkurchin** [comment]
Yeah, I might tweak one or two things once I'm putting the main module together, but looks generally fine to me! So should we merge this now or do you want to make those other changes on this branch?

**Comment by holdymoldy** [comment]
I made more small changes. Should be good to merge now!

**Pull request merged**
